version: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
  api:
    build: .
    environment:
      MONGO_URI: mongodb://mongo:27017/
      DB_NAME: peopledb
    depends_on: [mongo]
    ports: ["8000:8000"]
